import turtle
t=turtle.Turtle()
s=turtle.Screen()
s.bgcolor("black")
t.color("white")
t.shape("turtle")
t.pencolor("red")
t.pensize(3)
for i in range(5):
    t.fd(100)
    t.lt(144)
# t.lt(90)
# t.penup()
# t.fd(50)
# t.rt(90)
# t.pendown()
# for i in range(3):
#     t.fd(100)
#     t.rt(120)
turtle.done()